version: '3.9'

services:
  postgres:
    container_name: skeleton-graphql-postgres
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ../../artifacts/postgres:/var/lib/postgresql/data/
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
